server:
  port: 8086
spring:
  application:
    name: system_management
  datasource:
    url: jdbc:mysql://localhost:3306/sys_opensource?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&useSSL=true&characterEncoding=utf-8
    username: sys_opensource
    password: Kn7Hhz2yLPryBbXa
    dbcp2:
      min-idle: 10
      initial-size: 10
      max-total: 10
      max-wait-millis: 200
      driver-class-name: com.mysql.jdbc.Driver
      min-evictable-idle-time-millis: 300000
      time-between-eviction-runs-millis: 60000
    type: com.alibaba.druid.pool.DruidDataSource
  mvc:
    static-path-pattern: /**
  servlet:
    multipart:
      max-file-size: 10MB
#mybatis:
#  type-aliases-package: com.book.classroom.po
#  mapper-locations: classpath:mapper/*.xml
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#jwt:
#  header: Authorization
#  token-start-with: Bearer
#  base64-secret: c3RhcmZpbGVwZXJzb25hbDEyMzQ1Njc4OTBzdGFyZmlsZXBlcnNvbmFsMTIzNDU2Nzg5MHN0YXJmaWxlcGVyc29uYWwxMjM0NTY3ODkwXzEyMzQ1Njc4OTBfMTIzNDU2Nzg5MHJvb3RzdGFyZmlsbQ==
#  token-validity-in-seconds: 604800000
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml
